name: mhu_dart_proto
version: 1.0.3
description: Runtime library used by the protobuf meta generator
repository: https://github.com/maprohu/mhu_dart_proto

environment:
  sdk: '>=3.0.0 <4.0.0'

#dependency_overrides:
#  mhu_dart_commons:
#    path: ../mhu_dart_commons

dependencies:
  mhu_dart_commons: ^1.0.8

  collection: ^1.17.1
  protobuf:  ^3.0.0
  rxdart: ^0.27.7
  fast_immutable_collections: ^9.1.5
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  freezed: ^2.4.1

