name: mhu_dart_proto
version: 1.0.3
description: Runtime library used by the protobuf meta generator
repository: https://github.com/maprohu/mhu_dart_proto

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  mhu_dart_commons:
    path: ../mhu_dart_commons
  mhu_dart_builder:
    path: ../mhu_dart_builder
  mhu_dart_sourcegen:
    path: ../mhu_dart_sourcegen
  mhu_dart_annotation:
    path: ../mhu_dart_annotation

dependencies:
  mhu_dart_annotation: ^1.0.1
  mhu_dart_commons: ^1.0.9

  collection: ^1.17.1
  protobuf:  ^3.0.0
  rxdart: ^0.27.7
  fast_immutable_collections: ^9.1.5
  fixnum: ^1.1.0

dev_dependencies:
  mhu_dart_builder: ^1.0.3

  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  freezed: ^2.4.1

